In [1]:
%reload_ext rich

In [13]:
import os
import pandas as pd
import torch

In [14]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [7]:
data = pd.read_csv(data_file)
data

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [11]:
inputs, target = data.loc[:, ["NumRooms", "RoofType"]], data["Price"]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [15]:
inputs = inputs.fillna(inputs.mean())
inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True